#!/usr/bin/env python
#
# Script required for 'dennis' release tool.
#
# Takes arguments: <last version> <new version>
#
import os
import sys


def update_version(filename, old_version, new_version):
    filename = os.path.join(
        os.getcwd(), filename
    )

    with open(filename, 'r') as version_file:
        lines = version_file.readlines()

    with open(filename, 'w') as version_file:
        for line in lines:
            version_file.write(line.replace(old_version, new_version))


if __name__ == '__main__':

    if len(sys.argv) < 3:
        print('Missing arguments: <old version> <new version>')
        sys.exit(1)

    old_version = sys.argv[1].strip('v')
    new_version = sys.argv[2].strip('v')

    update_version('VERSION', old_version, new_version)
    update_version('setup.py', old_version, new_version)
